-- KODUCHI スキーマのテーブルとデータ（ADR 0010）。
--
-- 題材はデザインのサンプルクエリに揃えてある（events / orders / order_items /
-- refunds / user_traits / session_rollup）。デザインのクエリは PostgreSQL 方言で
-- 書かれているため、ここでは Oracle 方言に置き換えている。
--
-- EVENTS は 50,000 行を入れる。結果セットのカーソル分割取得（ADR 0003）が
-- 1,000 行ずつであるため、複数チャンクにまたがる表が 1 つ必要になる。

WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
SET ECHO ON

ALTER SESSION SET CONTAINER = FREEPDB1;

-- 利用者。
CREATE TABLE koduchi.users (
  user_id     NUMBER(12)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR2(255)   NOT NULL UNIQUE,
  display_name VARCHAR2(120),
  signed_up_at TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  country     VARCHAR2(2)
);

-- 利用者の属性。デザインの update 文が対象にしている表。
CREATE TABLE koduchi.user_traits (
  user_id      NUMBER(12) PRIMARY KEY REFERENCES koduchi.users (user_id),
  segment      VARCHAR2(32),
  sessions_28d NUMBER(8) DEFAULT 0 NOT NULL,
  updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- イベント。行数が多い表。
CREATE TABLE koduchi.events (
  event_id   NUMBER(12)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    NUMBER(12)    NOT NULL,
  channel    VARCHAR2(32)  NOT NULL,
  event_name VARCHAR2(64)  NOT NULL,
  created_at TIMESTAMP     NOT NULL,
  duration_ms NUMBER(10)
);

CREATE TABLE koduchi.orders (
  order_id   NUMBER(12)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    NUMBER(12)    NOT NULL,
  status     VARCHAR2(16)  NOT NULL,
  amount     NUMBER(12, 2) NOT NULL,
  currency   CHAR(3)       DEFAULT 'JPY' NOT NULL,
  created_at TIMESTAMP     NOT NULL
);

CREATE TABLE koduchi.order_items (
  order_item_id NUMBER(12)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      NUMBER(12)    NOT NULL REFERENCES koduchi.orders (order_id),
  sku           VARCHAR2(32)  NOT NULL,
  qty           NUMBER(6)     NOT NULL,
  unit_price    NUMBER(12, 2) NOT NULL
);

CREATE TABLE koduchi.refunds (
  refund_id  NUMBER(12)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   NUMBER(12)    NOT NULL REFERENCES koduchi.orders (order_id),
  amount     NUMBER(12, 2) NOT NULL,
  reason     VARCHAR2(200),
  created_at TIMESTAMP     NOT NULL
);

CREATE INDEX koduchi.ix_events_created ON koduchi.events (created_at);
CREATE INDEX koduchi.ix_events_user ON koduchi.events (user_id);
CREATE INDEX koduchi.ix_orders_user ON koduchi.orders (user_id);

-- 利用者 800 人。
INSERT INTO koduchi.users (user_id, email, display_name, signed_up_at, country)
SELECT
  LEVEL,
  'user' || LPAD(LEVEL, 4, '0') || '@example.com',
  CASE MOD(LEVEL, 4)
    WHEN 0 THEN '田中 ' || LEVEL
    WHEN 1 THEN '佐藤 ' || LEVEL
    WHEN 2 THEN 'Alice ' || LEVEL
    ELSE NULL
  END,
  SYSTIMESTAMP - NUMTODSINTERVAL(MOD(LEVEL * 7, 720), 'DAY'),
  CASE MOD(LEVEL, 3) WHEN 0 THEN 'JP' WHEN 1 THEN 'US' ELSE 'DE' END
FROM dual
CONNECT BY LEVEL <= 800;

INSERT INTO koduchi.user_traits (user_id, segment, sessions_28d)
SELECT
  user_id,
  CASE MOD(user_id, 5)
    WHEN 0 THEN 'power'
    WHEN 1 THEN 'active'
    WHEN 2 THEN 'casual'
    WHEN 3 THEN 'dormant'
    ELSE NULL
  END,
  MOD(user_id * 3, 45)
FROM koduchi.users;

-- イベント 50,000 行。
INSERT /*+ APPEND */ INTO koduchi.events (user_id, channel, event_name, created_at, duration_ms)
SELECT
  MOD(LEVEL, 800) + 1,
  CASE MOD(LEVEL, 6)
    WHEN 0 THEN 'organic search'
    WHEN 1 THEN 'paid social'
    WHEN 2 THEN 'referral'
    WHEN 3 THEN 'email'
    WHEN 4 THEN 'direct'
    ELSE 'paid search'
  END,
  CASE MOD(LEVEL, 4)
    WHEN 0 THEN 'page_view'
    WHEN 1 THEN 'add_to_cart'
    WHEN 2 THEN 'checkout'
    ELSE 'purchase'
  END,
  SYSTIMESTAMP - NUMTODSINTERVAL(MOD(LEVEL, 180), 'DAY') - NUMTODSINTERVAL(MOD(LEVEL * 13, 86400), 'SECOND'),
  CASE WHEN MOD(LEVEL, 17) = 0 THEN NULL ELSE MOD(LEVEL * 37, 9000) + 50 END
FROM dual
CONNECT BY LEVEL <= 50000;

COMMIT;

-- 注文 5,000 件。
INSERT INTO koduchi.orders (user_id, status, amount, created_at)
SELECT
  MOD(LEVEL, 800) + 1,
  CASE MOD(LEVEL, 8)
    WHEN 0 THEN 'refunded'
    WHEN 1 THEN 'cancelled'
    WHEN 2 THEN 'pending'
    ELSE 'paid'
  END,
  ROUND(MOD(LEVEL * 977, 90000) + 1200 + MOD(LEVEL, 97) / 100, 2),
  SYSTIMESTAMP - NUMTODSINTERVAL(MOD(LEVEL, 180), 'DAY')
FROM dual
CONNECT BY LEVEL <= 5000;

INSERT INTO koduchi.order_items (order_id, sku, qty, unit_price)
SELECT
  o.order_id,
  'SKU-' || LPAD(MOD(o.order_id * 3 + i.n, 240) + 1, 4, '0'),
  MOD(o.order_id + i.n, 4) + 1,
  ROUND(MOD(o.order_id * 131 + i.n * 17, 24000) + 300, 2)
FROM koduchi.orders o
CROSS JOIN (SELECT LEVEL AS n FROM dual CONNECT BY LEVEL <= 3) i
WHERE MOD(o.order_id + i.n, 5) <> 0;

-- 返金。amount > 20000 の行がデザインのサンプルクエリで参照される。
INSERT INTO koduchi.refunds (order_id, amount, reason, created_at)
SELECT
  order_id,
  ROUND(amount * 0.6, 2),
  CASE MOD(order_id, 3)
    WHEN 0 THEN '商品不良のため'
    WHEN 1 THEN 'お客様都合によるキャンセル'
    ELSE NULL
  END,
  created_at + NUMTODSINTERVAL(3, 'DAY')
FROM koduchi.orders
WHERE status = 'refunded';

COMMIT;

-- 週次のロールアップ。デザインのサンプルクエリが参照するビュー。
CREATE OR REPLACE VIEW koduchi.session_rollup AS
SELECT
  TRUNC(e.created_at, 'IW')                              AS week,
  e.channel                                              AS channel,
  COUNT(DISTINCT e.user_id)                              AS users,
  ROUND(AVG(e.duration_ms) / 1000, 2)                    AS avg_seconds,
  COUNT(*)                                               AS events
FROM koduchi.events e
GROUP BY TRUNC(e.created_at, 'IW'), e.channel;

-- スキーマツリーの「関数」枝を空にしないためのもの。
CREATE OR REPLACE FUNCTION koduchi.order_total(p_order_id IN NUMBER) RETURN NUMBER IS
  v_total NUMBER;
BEGIN
  SELECT NVL(SUM(qty * unit_price), 0)
    INTO v_total
    FROM koduchi.order_items
   WHERE order_id = p_order_id;
  RETURN v_total;
END;
/

-- DBMS_OUTPUT の確認用。メッセージタブが通知を拾えることを試せる。
CREATE OR REPLACE PROCEDURE koduchi.say_hello(p_times IN NUMBER DEFAULT 3) IS
BEGIN
  FOR i IN 1 .. p_times LOOP
    DBMS_OUTPUT.PUT_LINE('小槌からの通知 ' || i || ' 件目');
  END LOOP;
END;
/

BEGIN
  DBMS_STATS.GATHER_SCHEMA_STATS('KODUCHI');
END;
/

EXIT
