#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# macOS の Developer ID 署名と公証に要る資格情報を用意し、GitHub Secrets へ
# 入れるまでを案内する（ADR 0028）。
#
# **秘密は .env へ書かない。**この repo はパスワードを設定ファイルに置かない
# 方針であり（CLAUDE.md「設定ファイルの置き場所」）、ここで扱うのは証明書の
# 秘密鍵そのものである。ライブラリの write_env は使わず、GitHub Secrets へ
# 直に入れる。手元に落ちた .p12 と .p8 は最後に消すか尋ねる。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# 途中で作った一時ファイルは必ず片付ける。
WORK_DIR="$(mktemp -d)"
cleanup() { rm -rf "${WORK_DIR}"; }
trap cleanup EXIT

# base64 を 1 行で出す。macOS の base64 は折り返すため openssl を使う。
b64() { openssl base64 -A -in "$1"; }

# 入力されたパスを開いて確かめる。~ とドラッグ＆ドロップの引用符を外す。
normalize_path() {
  local p="$1"
  p="${p%\'}"; p="${p#\'}"
  p="${p%\"}"; p="${p#\"}"
  p="${p/#\~/$HOME}"
  printf '%s' "$p"
}

banner "koduchi: Developer ID 署名と公証の下ごしらえ"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "前提を確かめる"
say "始める前に、道具が揃っているかを見る。"

if [[ "$(uname -s)" != "Darwin" ]]; then
  warn "macOS でないと証明書の書き出しができない。中止する。"; exit 1
fi
say "macOS: $(sw_vers -productVersion)"

if xcrun --find notarytool >/dev/null 2>&1; then
  say "notarytool: あり"
else
  warn "notarytool が無い。Xcode か Command Line Tools を入れること。"
  note "  xcode-select --install"
  exit 1
fi

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh: 認証済み（$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || echo 'リポジトリ不明')）"
else
  warn "gh が使えない。Secrets の登録だけ手作業になる。"
fi

note "Apple Developer Program に加入済みであることが前提である。"
pause "続けるなら Enter"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Team ID を控える"
say "署名の検証に使う。秘密ではないので GitHub の variable に入れる。"
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "「Membership details」の Team ID（英数 10 桁）を控える。"
ask APPLE_TEAM_ID "Team ID を貼る:"
if [[ -z "${APPLE_TEAM_ID}" ]]; then
  warn "空のまま進む。あとで gh variable set APPLE_TEAM_ID で入れること。"
else
  set_var APPLE_TEAM_ID "${APPLE_TEAM_ID}"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "証明書署名要求（CSR）を作る"
say "Apple に証明書を発行してもらうための申請書を、手元の鍵から作る。"
note "Xcode を入れているなら Xcode → Settings → Accounts → Manage Certificates →"
note "「+」→ Developer ID Application でも作れる。その場合はこの段は飛ばしてよい。"
printf '\n'
open_url "https://support.apple.com/guide/keychain-access/request-a-certificate-from-a-certificate-authority-kyca2793/mac"
say "キーチェーンアクセスを開く。"
open -b com.apple.keychainaccess 2>/dev/null || warn "キーチェーンアクセスを手で開くこと。"
step "メニューバー「キーチェーンアクセス」→「証明書アシスタント」→「認証局に証明書を要求...」"
step "「ユーザのメールアドレス」に自分のメール、「通称」に鍵の名前（例: koduchi Developer ID）"
step "「CA のメールアドレス」は空のまま"
step "「ディスクに保存」を選び、「鍵ペア情報を指定」にチェック"
step "鍵ペア情報は既定のまま（RSA 2048 ビット）で保存"
pause "CSR（.certSigningRequest）を保存したら Enter"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Developer ID Application 証明書を発行して取り込む"
say "配布用の dmg に署名できるのはこの種類だけである。"
open_url "https://developer.apple.com/account/resources/certificates/add"
step "証明書の種類から「Developer ID Application」を選ぶ"
step "Profile Type は「G2 Sub-CA」（新しい方）を選ぶ"
step "さきほどの .certSigningRequest をアップロードして Continue"
step "できた .cer をダウンロードする（**まだダブルクリックしない**）"
printf '\n'
warn ".cer のダブルクリックは避けること。"
note "入り先が System キーチェーンになることがあり、そうなると秘密鍵（ログイン"
note "キーチェーンにある）と別々になって対にならない。ここでは取り込み先を"
note "はっきり指定して入れる。"
printf '\n'
ask CER_PATH_RAW "ダウンロードした .cer の場所を貼る:"
CER_PATH="$(normalize_path "${CER_PATH_RAW}")"

if [[ ! -f "${CER_PATH}" ]]; then
  warn "そのパスにファイルが無い: ${CER_PATH}"
  pause "手で ~/Library/Keychains/login.keychain-db へ入れてから Enter"
else
  security import "${CER_PATH}" -k "${HOME}/Library/Keychains/login.keychain-db" 2>&1 | sed 's/^/  /' || \
    warn "取り込みに失敗した（既に入っているだけかもしれない）"
fi

printf '\n'
say "中間証明書（Developer ID Certification Authority G2）も入れる。"
note "これが無いと信頼の鎖が切れ、署名しても検証で落ちる。"
if curl -fsS -o "${WORK_DIR}/DeveloperIDG2CA.cer" \
     "https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer"; then
  security import "${WORK_DIR}/DeveloperIDG2CA.cer" \
    -k "${HOME}/Library/Keychains/login.keychain-db" 2>&1 | sed 's/^/  /' || \
    note "既に入っているようだ"
else
  warn "中間証明書を取得できなかった。手で入れること:"
  note "  https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer"
fi

printf '\n'
say "証明書と秘密鍵が対になったかを見る:"
if security find-identity -v -p codesigning | grep -q "Developer ID Application"; then
  security find-identity -v -p codesigning | grep "Developer ID Application" | sed 's/^/  /'
  printf '  %s✓%s 対になった。これで .p12 に書き出せる。\n' "$GREEN" "$RESET"
else
  warn "まだ対になっていない。よくある原因は次の 2 つである。"
  note "  - 証明書が System キーチェーンに入っている（ログイン側へ入れ直す）"
  note "  - CSR を作った Mac と別の Mac で作業している（秘密鍵がそちらにある）"
  pause "直したら Enter（直らなくても先へ進める）"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "証明書を .p12 に書き出して Secrets へ入れる"
say "CI は鍵ごと要る。秘密鍵つきで書き出す。"
open -b com.apple.keychainaccess 2>/dev/null || true
step "キーチェーンアクセスの「ログイン」→「自分の証明書」を開く"
note "  ここに出ていなければ前の段で対になっていない。.p12 の形式も選べない。"
step "「Developer ID Application: ...」を右クリック →「\"...\" を書き出す...」"
step "フォーマットは「個人情報交換（.p12）」"
step "**パスワードを必ず付ける**（あとで訊く。使い捨てでよい）"
say ""
ask P12_PATH_RAW ".p12 を保存した場所を貼る（Finder からドラッグしてもよい）:"
P12_PATH="$(normalize_path "${P12_PATH_RAW}")"

if [[ ! -f "${P12_PATH}" ]]; then
  warn "そのパスにファイルが無い: ${P12_PATH}"
  SKIPPED+=("APPLE_CERTIFICATE と APPLE_CERTIFICATE_PASSWORD（.p12 が見つからなかった）")
else
  ask_secret APPLE_CERTIFICATE_PASSWORD ".p12 に付けたパスワード:"
  if openssl pkcs12 -in "${P12_PATH}" -passin "pass:${APPLE_CERTIFICATE_PASSWORD}" -nokeys -legacy >/dev/null 2>&1 \
    || openssl pkcs12 -in "${P12_PATH}" -passin "pass:${APPLE_CERTIFICATE_PASSWORD}" -nokeys >/dev/null 2>&1; then
    printf '  %s✓%s パスワードで開けた\n' "$GREEN" "$RESET"
  else
    warn "そのパスワードでは開けなかった。入れ違えているかもしれない。"
  fi
  set_secret APPLE_CERTIFICATE "$(b64 "${P12_PATH}")"
  set_secret APPLE_CERTIFICATE_PASSWORD "${APPLE_CERTIFICATE_PASSWORD}"
  printf '\n'
  if confirm "手元の .p12 を消すか？（Secrets に入ったので手元には要らない）"; then
    rm -f "${P12_PATH}" && say "消した: ${P12_PATH}"
  else
    warn "手元に秘密鍵が残る。git の管理下に置かないこと。"
  fi
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "App Store Connect API キーを作る"
say "公証（notarization）に使う。Apple ID のパスワードを CI に置かずに済む。"
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "「Team Keys」タブを開く（Individual Keys ではない）"
step "「+」でキーを作る。名前は任意（例: koduchi notarization）"
step "アクセス権は「Developer」で足りる"
step "**.p8 は 1 度しかダウンロードできない。**必ず保存すること"
step "同じ画面の「Key ID」と、上部の「Issuer ID」を控える"
pause "ダウンロードして Key ID / Issuer ID を控えたら Enter"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "API キーを Secrets へ入れる"
ask APPLE_API_KEY "Key ID を貼る:"
ask APPLE_API_ISSUER "Issuer ID を貼る（UUID の形）:"
ask P8_PATH_RAW ".p8 を保存した場所を貼る:"
P8_PATH="$(normalize_path "${P8_PATH_RAW}")"

if [[ ! -f "${P8_PATH}" ]]; then
  warn "そのパスにファイルが無い: ${P8_PATH}"
  SKIPPED+=("APPLE_API_KEY_P8（.p8 が見つからなかった）")
else
  set_secret APPLE_API_KEY_P8 "$(b64 "${P8_PATH}")"
fi
[[ -n "${APPLE_API_KEY}" ]] && set_secret APPLE_API_KEY "${APPLE_API_KEY}"
[[ -n "${APPLE_API_ISSUER}" ]] && set_secret APPLE_API_ISSUER "${APPLE_API_ISSUER}"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "通るか確かめる"
say "資格情報が本当に使えるかを、Apple に問い合わせて確かめる。"

if [[ -f "${P8_PATH:-}" && -n "${APPLE_API_KEY:-}" && -n "${APPLE_API_ISSUER:-}" ]]; then
  say "notarytool に資格情報を検証させる（送信はしない）..."
  if xcrun notarytool history \
      --key "${P8_PATH}" --key-id "${APPLE_API_KEY}" --issuer "${APPLE_API_ISSUER}" \
      >/dev/null 2>&1; then
    printf '  %s✓%s API キーで公証サービスに繋がった\n' "$GREEN" "$RESET"
  else
    warn "公証サービスに繋がらなかった。Key ID / Issuer ID / .p8 の対応を見直すこと。"
  fi
  printf '\n'
  if confirm "手元の .p8 を消すか？（Secrets に入ったので手元には要らない）"; then
    rm -f "${P8_PATH}" && say "消した: ${P8_PATH}"
  else
    warn "手元に API の秘密鍵が残る。git の管理下に置かないこと。"
  fi
else
  note "API キーが揃っていないので、繋がるかの確認は飛ばす。"
fi

printf '\n'
say "GitHub に入った Secrets:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret list 2>/dev/null | sed 's/^/  /' || warn "一覧を取れなかった"
fi

finish
printf '  次は %sv* タグを push%s すればリリースのワークフローが署名と公証を行う。\n' "$BOLD" "$RESET"
printf '  仕組みと決めごとは %sadr/0028-配布物の署名と公証.md%s にある。\n\n' "$BOLD" "$RESET"
